name: CD
on:
 push:
  branches:
    - main
  paths:
    - '**'
 workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        default: 'vsanchezr33/sample-angular-app:0.0.1'
jobs:
  pull-DockerFiles:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Pull Dockerfile
        run: |
         docker pull ${{ inputs.image_name }}
      - name: Run Docker container
        run: |
          docker run -d --name angular_aplication -p 80:8080 ${{ inputs.image_name }}

      - name: Wait 30 seconds for container to start 
        run: sleep 30
      - name: Docker ps
        run: |
          docker ps

      - name: Curl the deployed application
        run: |
          curl -I http://localhost:80
        